### PR TITLE
Changing backspace from "⇐" to "⌫"

### PR DESCRIPTION
**Pull request by denilsonsa**
I believe ⌫ character (U+232B ERASE TO THE LEFT) is more appropriate to Backspace.

There is also the opposite: ⌦ (U+2326 ERASE TO THE RIGHT); which may be appropriate for "delete" key, but the current "Del" text seems more intuitive.

On a completely unrelated topic… How did you record that animated GIF? It looks clean, without ugly compression artifacts. How did you do it?

### CODE REVIEW

**Comment by denilsonsa** [comment]
It might be easier to merge #2 before merging this one.

**Comment by seletskiy** [comment]
Can you rebase this PR?

**Comment by denilsonsa** [comment]
Done. Fixed the merge for you.

**Comment by seletskiy** [comment]
Thanks! You're awesome!

**Comment by seletskiy** [comment]
@denilsonsa: Sorry for ignoring your question about recording gifs.

I'm using self-made scripts, which are trying to achieve lossless compression.

First one is a video-recorder: https://github.com/seletskiy/dotfiles/blob/master/bin/record-cast
Second one is a video-to-gif converter: https://github.com/seletskiy/dotfiles/blob/master/bin/video-to-gif

I've tried to use some ready software, but turn-off points was either ugly compression or incompatibility with tile window manager.

**Comment by denilsonsa** [comment]
For future reference, these are the dependencies:
- [gifsicle](http://www.lcdf.org/gifsicle/)
- [FFcast](https://github.com/lolilolicon/FFcast) or [ffcast](https://github.com/minos-org/ffcast)
- ffmpeg
- [xdotool](http://www.semicomplete.com/projects/xdotool/)

@seletskiy, I have some questions:
- Why are you first capturing at 25fps and later converting to PNGs at 10fps? Can't you capture already at 10fps? Or maybe 30fps? Can't you capture directly to PNG images, or would that be too CPU-intensive?
- You are building PNG images at 10fps, which means 10cs (100ms) of interval between them; but you are building a GIF with 8cs (80ms) of delay. So, you are speeding up the resulting animation by around 25%. Are you aware of that?
- Did you know you may achieve higher compression (i.e. smaller GIF size) by using `--optimize=3` or `-O3`? Maybe just `-O2` could be enough. (I just read it at the [manpage](http://www.lcdf.org/gifsicle/man.html))

**Comment by seletskiy** [comment]
@denilsonsa: I don't remember much of implementation details.

Honestly, I even didn't think about

**Comment by seletskiy** [comment]
@denilsonsa: I don't remember much of implementation details.

Honestly, I didn't even think about framerate, so it's pure coincidence. But it can be useful for recording video in higher framerate, because it can be downsampled if required.

I worked around different timings in gif, and ended up with that timeout by subjective opinion. I guess it can be aligned to same value without any visible differences.

Regarding compression: I think that it actually should be smart enough to strip color pallete to lowest as possible. It will lead to significant size reduction.

If you will fix that issues you mentioned about I'll glad to see fixed code :)

**Comment by seletskiy** [comment]
BTW, look at https://github.com/seletskiy/dotfiles/blob/master/bin/record-terminal. It's intented to work with i3 tile window manager. It places screenkey on top of terminal automatically.

**Pull request merged**
